#!/usr/bin/env python3
"""
将 CA 覆盖国家名单合并进 public/data/ca-registry.json
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / 'public' / 'data' / 'ca-registry.json'

# UN 标准国名 → ISO2
COVERAGE_COUNTRIES = {
    'Afghanistan': 'AF',
    'Albania': 'AL',
    'Algeria': 'DZ',
    'Andorra': 'AD',
    'Angola': 'AO',
    'Antigua and Barbuda': 'AG',
    'Argentina': 'AR',
    'Armenia': 'AM',
    'Australia': 'AU',
    'Austria': 'AT',
    'Azerbaijan': 'AZ',
    'Bahamas': 'BS',
    'Bahrain': 'BH',
    'Bangladesh': 'BD',
    'Barbados': 'BB',
    'Belarus': 'BY',
    'Belgium': 'BE',
    'Belize': 'BZ',
    'Benin': 'BJ',
    'Bhutan': 'BT',
    'Bolivia (Plurinational State of)': 'BO',
    'Bosnia and Herzegovina': 'BA',
    'Botswana': 'BW',
    'Brazil': 'BR',
    'Brunei Darussalam': 'BN',
    'Bulgaria': 'BG',
    'Burkina Faso': 'BF',
    'Burundi': 'BI',
    'Cabo Verde': 'CV',
    'Cambodia': 'KH',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Central African Republic': 'CF',
    'Chad': 'TD',
    'Chile': 'CL',
    'China': 'CN',
    'Colombia': 'CO',
    'Comoros': 'KM',
    'Congo': 'CG',
    'Cook Islands': 'CK',
    'Costa Rica': 'CR',
    "Côte d'Ivoire": 'CI',
    'Croatia': 'HR',
    'Cuba': 'CU',
    'Cyprus': 'CY',
    'Czechia': 'CZ',
    "Democratic People's Republic of Korea": 'KP',
    'Democratic Republic of the Congo': 'CD',
    'Denmark': 'DK',
    'Djibouti': 'DJ',
    'Dominica': 'DM',
    'Dominican Republic': 'DO',
    'Ecuador': 'EC',
    'Egypt': 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    'Eritrea': 'ER',
    'Estonia': 'EE',
    'Eswatini': 'SZ',
    'Ethiopia': 'ET',
    'Fiji': 'FJ',
    'Finland': 'FI',
    'France': 'FR',
    'Gabon': 'GA',
    'Gambia': 'GM',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Greece': 'GR',
    'Grenada': 'GD',
    'Guatemala': 'GT',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Guyana': 'GY',
    'Haiti': 'HT',
    'Honduras': 'HN',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'India': 'IN',
    'Indonesia': 'ID',
    'Iran (Islamic Republic of)': 'IR',
    'Iraq': 'IQ',
    'Ireland': 'IE',
    'Israel': 'IL',
    'Italy': 'IT',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Jordan': 'JO',
    'Kazakhstan': 'KZ',
    'Kenya': 'KE',
    'Kiribati': 'KI',
    'Kuwait': 'KW',
    'Kyrgyzstan': 'KG',
    "Lao People's Democratic Republic": 'LA',
    'Latvia': 'LV',
    'Lebanon': 'LB',
    'Lesotho': 'LS',
    'Liberia': 'LR',
    'Libya': 'LY',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Madagascar': 'MG',
    'Malawi': 'MW',
    'Malaysia': 'MY',
    'Maldives': 'MV',
    'Mali': 'ML',
    'Malta': 'MT',
    'Marshall Islands': 'MH',
    'Mauritania': 'MR',
    'Mauritius': 'MU',
    'Mexico': 'MX',
    'Micronesia (Federated States of)': 'FM',
    'Monaco': 'MC',
    'Mongolia': 'MN',
    'Montenegro': 'ME',
    'Morocco': 'MA',
    'Mozambique': 'MZ',
    'Myanmar': 'MM',
    'Namibia': 'NA',
    'Nauru': 'NR',
    'Nepal': 'NP',
    'Netherlands': 'NL',
    'New Zealand': 'NZ',
    'Nicaragua': 'NI',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'North Macedonia': 'MK',
    'Norway': 'NO',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Palau': 'PW',
    'Panama': 'PA',
    'Papua New Guinea': 'PG',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Philippines': 'PH',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Qatar': 'QA',
    'Republic of Korea': 'KR',
    'Republic of Moldova': 'MD',
    'Romania': 'RO',
    'Russian Federation': 'RU',
    'Rwanda': 'RW',
    'Saint Kitts and Nevis': 'KN',
    'Saint Lucia': 'LC',
    'Saint Vincent and the Grenadines': 'VC',
    'Samoa': 'WS',
    'San Marino': 'SM',
    'Sao Tome and Principe': 'ST',
    'Saudi Arabia': 'SA',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapore': 'SG',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Solomon Islands': 'SB',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'South Sudan': 'SS',
    'Spain': 'ES',
    'Sri Lanka': 'LK',
    'Sudan': 'SD',
    'Suriname': 'SR',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Syrian Arab Republic': 'SY',
    'Tajikistan': 'TJ',
    'Thailand': 'TH',
    'Timor-Leste': 'TL',
    'Togo': 'TG',
    'Tonga': 'TO',
    'Trinidad and Tobago': 'TT',
    'Tunisia': 'TN',
    'Türkiye': 'TR',
    'Turkmenistan': 'TM',
    'Tuvalu': 'TV',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'United Republic of Tanzania': 'TZ',
    'United States': 'US',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Vanuatu': 'VU',
    'Venezuela (Bolivarian Republic of)': 'VE',
    'Viet Nam': 'VN',
    'Yemen': 'YE',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
}

ISO_TO_REGION = {
    'US': 'North America', 'CA': 'North America', 'MX': 'North America',
    'GT': 'Latin America', 'BZ': 'Latin America', 'SV': 'Latin America',
    'HN': 'Latin America', 'NI': 'Latin America', 'CR': 'Latin America',
    'PA': 'Latin America', 'CU': 'Latin America', 'DO': 'Latin America',
    'HT': 'Latin America', 'JM': 'Latin America', 'TT': 'Latin America',
    'BB': 'Latin America', 'AG': 'Latin America', 'DM': 'Latin America',
    'GD': 'Latin America', 'KN': 'Latin America', 'LC': 'Latin America',
    'VC': 'Latin America', 'BS': 'Latin America', 'BR': 'Latin America',
    'AR': 'Latin America', 'CL': 'Latin America', 'CO': 'Latin America',
    'PE': 'Latin America', 'VE': 'Latin America', 'EC': 'Latin America',
    'BO': 'Latin America', 'PY': 'Latin America', 'UY': 'Latin America',
    'GY': 'Latin America', 'SR': 'Latin America',
    'GB': 'Europe', 'IE': 'Europe', 'FR': 'Europe', 'DE': 'Europe',
    'ES': 'Europe', 'PT': 'Europe', 'IT': 'Europe', 'NL': 'Europe',
    'BE': 'Europe', 'LU': 'Europe', 'AT': 'Europe', 'CH': 'Europe',
    'SE': 'Europe', 'NO': 'Europe', 'DK': 'Europe', 'FI': 'Europe',
    'IS': 'Europe', 'PL': 'Europe', 'CZ': 'Europe', 'SK': 'Europe',
    'HU': 'Europe', 'RO': 'Europe', 'BG': 'Europe', 'GR': 'Europe',
    'HR': 'Europe', 'SI': 'Europe', 'RS': 'Europe', 'BA': 'Europe',
    'ME': 'Europe', 'MK': 'Europe', 'AL': 'Europe', 'EE': 'Europe',
    'LV': 'Europe', 'LT': 'Europe', 'UA': 'Europe', 'BY': 'Europe',
    'MD': 'Europe', 'CY': 'Europe', 'MT': 'Europe', 'AD': 'Europe',
    'MC': 'Europe', 'SM': 'Europe', 'RU': 'Europe',
    'CN': 'Asia Pacific', 'JP': 'Asia Pacific', 'KR': 'Asia Pacific',
    'HK': 'Asia Pacific', 'IN': 'Asia Pacific', 'PK': 'Asia Pacific',
    'BD': 'Asia Pacific', 'TH': 'Asia Pacific', 'VN': 'Asia Pacific',
    'MY': 'Asia Pacific', 'SG': 'Asia Pacific', 'ID': 'Asia Pacific',
    'PH': 'Asia Pacific', 'AU': 'Asia Pacific', 'NZ': 'Asia Pacific',
    'KZ': 'Asia Pacific', 'UZ': 'Asia Pacific', 'MN': 'Asia Pacific',
    'NP': 'Asia Pacific', 'LK': 'Asia Pacific', 'MM': 'Asia Pacific',
    'KH': 'Asia Pacific', 'LA': 'Asia Pacific', 'FJ': 'Asia Pacific',
    'PG': 'Asia Pacific', 'TL': 'Asia Pacific', 'BN': 'Asia Pacific',
    'AF': 'Asia Pacific', 'BT': 'Asia Pacific', 'MV': 'Asia Pacific',
    'KP': 'Asia Pacific', 'KG': 'Asia Pacific', 'TJ': 'Asia Pacific',
    'TM': 'Asia Pacific', 'AZ': 'Asia Pacific', 'AM': 'Asia Pacific',
    'GE': 'Asia Pacific', 'CK': 'Asia Pacific', 'KI': 'Asia Pacific',
    'MH': 'Asia Pacific', 'FM': 'Asia Pacific', 'PW': 'Asia Pacific',
    'NR': 'Asia Pacific', 'TV': 'Asia Pacific', 'WS': 'Asia Pacific',
    'TO': 'Asia Pacific', 'SB': 'Asia Pacific', 'VU': 'Asia Pacific',
    'AE': 'Middle East & Africa', 'SA': 'Middle East & Africa',
    'IL': 'Middle East & Africa', 'TR': 'Middle East & Africa',
    'IQ': 'Middle East & Africa', 'IR': 'Middle East & Africa',
    'JO': 'Middle East & Africa', 'LB': 'Middle East & Africa',
    'KW': 'Middle East & Africa', 'OM': 'Middle East & Africa',
    'QA': 'Middle East & Africa', 'BH': 'Middle East & Africa',
    'YE': 'Middle East & Africa', 'EG': 'Middle East & Africa',
    'ZA': 'Middle East & Africa', 'NG': 'Middle East & Africa',
    'KE': 'Middle East & Africa', 'GH': 'Middle East & Africa',
    'TZ': 'Middle East & Africa', 'ET': 'Middle East & Africa',
    'MA': 'Middle East & Africa', 'DZ': 'Middle East & Africa',
    'TN': 'Middle East & Africa', 'AO': 'Middle East & Africa',
    'MZ': 'Middle East & Africa', 'ZM': 'Middle East & Africa',
    'ZW': 'Middle East & Africa', 'UG': 'Middle East & Africa',
    'SN': 'Middle East & Africa', 'CI': 'Middle East & Africa',
    'CM': 'Middle East & Africa', 'SD': 'Middle East & Africa',
    'SS': 'Middle East & Africa', 'RW': 'Middle East & Africa',
    'BW': 'Middle East & Africa', 'NA': 'Middle East & Africa',
    'MG': 'Middle East & Africa', 'ML': 'Middle East & Africa',
    'BF': 'Middle East & Africa', 'NE': 'Middle East & Africa',
    'TD': 'Middle East & Africa', 'LY': 'Middle East & Africa',
    'SO': 'Middle East & Africa', 'CD': 'Middle East & Africa',
    'CG': 'Middle East & Africa', 'GA': 'Middle East & Africa',
    'GN': 'Middle East & Africa', 'SL': 'Middle East & Africa',
    'LR': 'Middle East & Africa', 'BJ': 'Middle East & Africa',
    'BI': 'Middle East & Africa', 'CF': 'Middle East & Africa',
    'TD': 'Middle East & Africa', 'DJ': 'Middle East & Africa',
    'ER': 'Middle East & Africa', 'GM': 'Middle East & Africa',
    'GW': 'Middle East & Africa', 'CV': 'Middle East & Africa',
    'KM': 'Middle East & Africa', 'ST': 'Middle East & Africa',
    'SC': 'Middle East & Africa', 'MU': 'Middle East & Africa',
    'MR': 'Middle East & Africa', 'MW': 'Middle East & Africa',
    'LS': 'Middle East & Africa', 'SZ': 'Middle East & Africa',
    'SY': 'Middle East & Africa', 'TG': 'Middle East & Africa',
}


def display_name(un_name: str) -> str:
    aliases = {
        'Czechia': 'Czech Republic',
        'United States': 'United States',
        'Viet Nam': 'Vietnam',
        'Republic of Korea': 'South Korea',
        "Democratic People's Republic of Korea": 'North Korea',
        'Russian Federation': 'Russia',
        'Republic of Moldova': 'Moldova',
        'Türkiye': 'Turkey',
        'Syrian Arab Republic': 'Syria',
        'Iran (Islamic Republic of)': 'Iran',
        'Venezuela (Bolivarian Republic of)': 'Venezuela',
        'Bolivia (Plurinational State of)': 'Bolivia',
        'Brunei Darussalam': 'Brunei',
        "Lao People's Democratic Republic": 'Laos',
        'Micronesia (Federated States of)': 'Micronesia',
        'United Republic of Tanzania': 'Tanzania',
        'Sao Tome and Principe': 'Sao Tome and Principe',
    }
    return aliases.get(un_name, un_name)


def main() -> None:
    data = json.loads(REGISTRY_PATH.read_text(encoding='utf-8'))
    existing = {c['iso2']: c for c in data.get('countries', [])}
    provider_isos = set()
    for p in data.get('providers', []):
        for iso in p.get('countries', []):
            provider_isos.add(iso)

    added = 0
    updated = 0
    for name, iso in COVERAGE_COUNTRIES.items():
        region = ISO_TO_REGION.get(iso, 'Europe')
        entry = existing.get(iso)
        if entry:
            entry['coverageSupported'] = True
            entry['enabled'] = True
            if not entry.get('region'):
                entry['region'] = region
            updated += 1
        else:
            existing[iso] = {
                'iso2': iso,
                'name': display_name(name),
                'region': region,
                'enabled': True,
                'coverageSupported': True,
                'sortOrder': len(existing) + 1,
            }
            added += 1

    countries = sorted(existing.values(), key=lambda c: c['name'])
    for i, c in enumerate(countries, 1):
        c['sortOrder'] = i

    data['countries'] = countries
    meta = data.setdefault('meta', {})
    meta['coverageCountryCount'] = len(COVERAGE_COUNTRIES)
    meta['coverageMergedAt'] = __import__('datetime').date.today().isoformat()

    REGISTRY_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding='utf-8',
    )
    print(f'覆盖国家 {len(COVERAGE_COUNTRIES)} 个，新增 {added}，更新 {updated}')
    print(f'registry 共 {len(countries)} 国，其中 {len(provider_isos)} 国有 Provider 数据')


if __name__ == '__main__':
    main()
